name: Meson MacOS Test

on:
  push:
    branches: [ 3.3-stable-meson ]
  pull_request:
    branches: [ 3.3-stable-meson ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.1
      with:
        action: test
        directory: build
        setup-options: '-Ddefault_library=both'
        options: --verbose
        meson-version: 0.54.1
        ninja-version: 1.9.0.post1
        gcovr-version: 4.2
